### PR TITLE
#230: Initialize ConnectionFactory at application startup

### LINKED ISSUE #230: Artemis ConnectionFactory registered under ApplicationScope, does not register XAResourceRecovery on application start
The Artemis ConnectionFactory [gets registered ](https://github.com/quarkiverse/quarkus-artemis/blob/main/jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java#L104) as ApplicationScoped [1], which means its lazily instantiated when a method is invoked.
As a result it does not register an `XAResourceRecovery` at application startup. This makes it impossible to recover pending XA transactions when restarting after a crash.

### PR DESCRIPTION
**Pull request by turing85**
- Update turing85/publish-report from 1.0.6 to 1.0.8

Resolves #230

### CODE REVIEW

**Review by zhfeng — APPROVED** [review]

**Comment by zhfeng** [comment]
@turing85 Please holding on this PR and I will discuss further with @tmielke. Thanks!

**Comment by turing85** [comment]
> @turing85 Please holding on this PR and I will discuss further with @tmielke. Thanks!

I am waiting for at least one more approval from either @middagj or @louisa-fr anyway :slightly_smiling_face:

**Review by middagj — APPROVED** [review]

**Comment by turing85** [comment]
Oh. Looks like github-actions have issues again.

**Comment by zhfeng** [comment]
@turing85 I update to add a change to init the ConnectionFactory at startup time which could give `quarkus-pooled-jms` chances to register `XAResourceRecovery` when starting the application.

Our demo is like

```java
@Path("/hello")
public class GreetingResource {
    @Inject
    TransactionManager transactionManager;

    @Inject
    DataSource dataSource;

    @Inject
    ConnectionFactory connectionFactory;

   @POST
    @Produces(MediaType.TEXT_PLAIN)
    @Transactional
    public String hello(String message) throws Exception {
        //It simulates a JVM crash when receving a crash message
        DummyXAResource xaResource = new DummyXAResource("crash".equals(message));
        transactionManager.getTransaction().enlistResource(xaResource);

        doSomething with database and MQ;
    }
```

Without my changes on `ArtemisJmsRecorder`, we have to add `@Startup` on `GreetingResource` to let qarkus Arc to instantiate inject `ConnectionFactory` to make recovery working. From user perspective, it looks like a trick when restarting the applcation after crash happens.

 @tmielke what do you think? and can you check it with your demo? Thanks!

**Comment by zhfeng** [comment]
Also it seems `agroal` is doing the same thing. See https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/AgroalRecorder.java#L21-L30

**Comment by tmielke** [comment]
I confirm the proposed fix from Zheng makes my example do XA recovery correctly. I have no longer a need to configure the GreetingResource class with the `@Startup` annotation.

**Comment by turing85** [comment]
> @turing85 I update to add a change to init the ConnectionFactory at startup time which could give `quarkus-pooled-jms` chances to register `XAResourceRecovery` when starting the application.
> 
> Our demo is like
> 
> ```java
> @Path("/hello")
> public class GreetingResource {
>     @Inject
>     TransactionManager transactionManager;
> 
>     @Inject
>     DataSource dataSource;
> 
>     @Inject
>     ConnectionFactory connectionFactory;
> 
>    @POST
>     @Produces(MediaType.TEXT_PLAIN)
>     @Transactional
>     public String hello(String message) throws Exception {
>         //It simulates a JVM crash when receving a crash message
>         DummyXAResource xaResource = new DummyXAResource("crash".equals(message));
>         transactionManager.getTransaction().enlistResource(xaResource);
> 
>         doSomething with database and MQ;
>     }
> ```
> 
> Without my changes on `ArtemisJmsRecorder`, we have to add `@Startup` on `GreetingResource` to let qarkus Arc to instantiate inject `ConnectionFactory` to make recovery working. From user perspective, it looks like a trick when restarting the applcation after crash happens.
> 
> @tmielke what do you think? and can you check it with your demo? Thanks!

@zhfeng LGTM. We still need the bean to be a `@Singleton` though, right? Or can we go back to `@ApplicationScoped`?

**Comment by zhfeng** [comment]
@turing85 Good point! I think we can go back `@ApplicationScoped`. Let's check it again.

**Comment by zhfeng** [comment]
@turing85 Yeah, I confirm that `@ApplicationScoped` is still working. Anyway, since SyntheticBean is not controlled by Quarkus Arc and we init it at startup time. So @mkouba, is there anything we missed on CDI side? Do you see any risk if we go back to `@ApplicationScoped`?

**Comment by zhfeng** [comment]
Thanks @mkouba for your inputs!

@turing85 feel free to roll back to use `@ApplicationScoped` and go ahead to squash commits.

**Comment by turing85** [comment]
> Thanks @mkouba for your inputs!
> 
> @turing85 feel free to roll back to use `@ApplicationScoped` and go ahead to squash commits.

@zhfeng I took the liberty and algined the `ArtemisCoreRecorder` with the `ArtemisJmsRecorcer`:

old:
https://github.com/quarkiverse/quarkus-artemis/blob/be1a9e2263d3aae478f550982b05334e145fa9bb/core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java#L20-L22

new:
https://github.com/quarkiverse/quarkus-artemis/blob/d6caf84f119f2033fa033078fe14ca227359c787/core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java#L22

If you give the go-ahead (by re-approving), then I'll merge, release & downstream the change.

**Review by middagj — APPROVED** [review]
Perhaps you want to change the PR title

**Review by zhfeng — APPROVED** [review]

**Pull request merged**
