### PR TITLE
Release 3.2.0

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
@turing85 @middagj is there anything else needed to add?

**Comment by turing85** [comment]
lgtm :slightly_smiling_face:

**Review by turing85 — APPROVED** [review]

**Comment by turing85** [comment]
I am somewhat torn whether we should release. Quarkus released `3.8.1` some hours ago. And we could also wait for the corresponding quarkus-camel bump.

**Comment by turing85** [comment]
[quarkus 3.8.1](https://github.com/quarkiverse/quarkus-artemis/pull/423) and [quarkus-camel-bom 3.8.1](https://github.com/quarkiverse/quarkus-artemis/pull/424) have landed. @zhfeng do you want to rebase?

**Comment by zhfeng** [comment]
OK, rebase is done.

**Comment by turing85** [comment]
looks great! I'll merge as soon as the tests complete

**Pull request merged**
