### PR TITLE
Release

### PR DESCRIPTION
**Pull request by turing85**

### CODE REVIEW

**Comment by turing85** [comment]
@vsevel @gastaldi @zhfeng Before we merge this one: do you plan a release of `quarkus-pooled-jms` and/or `quarkus-ironjacamar` for Quarkus 3.13.0?

We need to make a minor bump since this is the first release after the jandex-index update.

**Comment by gastaldi** [comment]
No planned releases for `quarkus-ironjacamar` so far

**Comment by turing85** [comment]
Okay, I just double-checked; we have no dependency on `pooled-jms`, so we are good to go.

**Comment by vsevel** [comment]
I integrated `3.4.0` in my quarkus `3.13` test app and verified that all was ok. 
thanks for the quick fixes and releases @turing85 @gastaldi @zhfeng

**Pull request merged**
