### PR TITLE
Add ArtemisJmsRABuildItem

### LINKED ISSUE #580: health check fails with java.lang.IllegalArgumentException: port out of range:-1
when I call `/q/health` on an application running the jca adapter, and connected **successfully** to a hornetq cluster, I get the following exception:
```
2024-07-31 12:02:44,006 INFO  [org.acm.MyProducer] (executor-thread-1) sending jms message Wed Jul 31 12:02:44 CEST 2024 from host=x
2024-07-31 12:02:49,008 INFO  [org.acm.MyProducer] (executor-thread-1) sending jms message Wed Jul 31 12:02:49 CEST 2024 from host=x
2024-07-31 12:02:54,016 INFO  [org.acm.MyProducer] (executor-thread-2) sending jms message Wed Jul 31 12:02:54 CEST 2024 from host=x

...
2024-07-31 12:02:56,066 WARN  [org.apa.act.art.cor.client] (executor-thread-1) AMQ212007: connector.create or connectorFactory.createConnector should never throw an exception, implementation is badly behaved, but we will deal with it anyway.: java.lang.IllegalArgumentException: port out of range:-1
        at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:153)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:234)
        at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.createConnection(NettyConnector.java:885)
        at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.createConnection(NettyConnector.java:877)
        at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.createConnection(NettyConnector.java:859)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.openTransportConnection(ClientSessionFactoryImpl.java:1222)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createTransportConnection(ClientSessionFactoryImpl.java:1343)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createTransportConnection(ClientSessionFactoryImpl.java:1263)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.establishNewConnection(ClientSessionFactoryImpl.java:1506)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnection(ClientSessionFactoryImpl.java:1084)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnectionWithRetry(ClientSessionFactoryImpl.java:969)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.connect(ClientSessionFactoryImpl.java:287)
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.connect(ClientSessionFactoryImpl.java:303)
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:718)
        at org.apache.activemq.artemis.api.core.client.ServerLocator_JD5VznKFNQ2EhTb-yyf2Ep9BRq8_Synthetic_ClientProxy.createSessionFactory(Unknown Source)
        at io.quarkus.artemis.core.runtime.health.ServerLocatorHealthCheck.call(ServerLocatorHealthCheck.java:79)
        at io.quarkus.artemis.core.runtime.health.ServerLocatorHealthCheck_ClientProxy.call(Unknown Source)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-07-31 12:02:56,091 INFO  [io.sma.health] (vert.x-eventloop-thread-0) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Artemis Core health check","status":"DOWN","data":{"<default>":"DOWN"}}]}

```

I am using the same reproducer described in https://github.com/quarkiverse/quarkus-artemis/issues/567, except I added:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
```

when I look at the `serverLocators` in `ServerLocatorHealthCheck` I see:
```
<default> -> {ServerLocator_JD5VznKFNQ2EhTb-yyf2Ep9BRq8_Synthetic_ClientProxy@5708} "ServerLocatorImpl [initialConnectors=[TransportConfiguration(name=null, factory=org-apache-activemq-artemis-core-remoting-impl-netty-NettyConnectorFactory)?port=-1&host=null], discoveryGroupConfiguration=null]"
```

I am just wondering if this health check supports connections created from the jca adapter.
cc @zhfeng @gastaldi

### PR DESCRIPTION
**Pull request by zhfeng**
It could fix #580 partly, and we still need to consider how to do the health check in `quarkus-artemis-ra`.

### CODE REVIEW

**Comment by zhfeng** [comment]
@vsevel can you check this fix with your project?

**Comment by vsevel** [comment]
I now get:
```
$ curl localhost:9000/q/health/ready
        {
            "name": "Artemis JMS Resource Adaptor health check",
            "status": "UP",
            "data": {
                "<default>": "UP"
            }
        }

```

deps:
```
$ ls -al target/quarkus-app/lib/main | grep -E "artemis|iron"
-rw-r--r-- 1 Sevel 1049089   22029 Aug  2 11:51 io.quarkiverse.artemis.quarkus-artemis-core-999-SNAPSHOT.jar
-rw-r--r-- 1 Sevel 1049089   11146 Aug  2 11:51 io.quarkiverse.artemis.quarkus-artemis-jms-ra-999-SNAPSHOT.jar
-rw-r--r-- 1 Sevel 1049089   53855 Aug  2 11:51 io.quarkiverse.ironjacamar.quarkus-ironjacamar-1.3.2.jar
-rw-r--r-- 1 Sevel 1049089  676595 Aug  2 08:44 org.apache.activemq.artemis-commons-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089  829150 Aug  2 08:44 org.apache.activemq.artemis-core-client-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089   21552 Aug  2 08:44 org.apache.activemq.artemis-hqclient-protocol-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089  187781 Aug  2 08:44 org.apache.activemq.artemis-jakarta-client-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089  160114 Aug  2 08:44 org.apache.activemq.artemis-jakarta-ra-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089   33311 Aug  2 08:44 org.apache.activemq.artemis-jakarta-service-extensions-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089  112139 Aug  2 08:44 org.apache.activemq.artemis-selector-2.36.0.jar
-rw-r--r-- 1 Sevel 1049089  103566 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-common-api-3.0.9.Final.jar
-rw-r--r-- 1 Sevel 1049089   57849 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-core-api-3.0.9.Final.jar
-rw-r--r-- 1 Sevel 1049089  502175 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-core-impl-3.0.9.Final.jar
```

seems everything is working nicely. what would you say that it only partially fixes the issue @zhfeng ? what would be still missing? some additional checks we could do in the artemis RA?
I am surprised with the impl of:
```
    public HealthCheckResponse call() {
        HealthCheckResponseBuilder builder = HealthCheckResponse.named("Artemis JMS Resource Adaptor health check").up();
        for (String name : connectionFactoryNames) {
            Annotation identifier = ArtemisUtil.toIdentifier(name);
            try (Connection ignored = connectionFactories.select(identifier).get().createConnection()) {
                builder.withData(name, "UP");
            } catch (Exception e) {
                builder.withData(name, "DOWN").down();
            }
        }
        return builder.build();
    }
```

do you want the status to be always `UP`?
or should the status be `DOWN` as soon as at least one connection factory is down?

**Comment by zhfeng** [comment]
Thanks @vsevel - that's great to hear it is working!

I mean partially fix when only introducing the `ArtemisJmsRABuildItem`. Now I think we almost get to fix the issue :)

@turing85 what do you think about the status? I just bowrrow your codes from the `quarkus-artemis-jms`.

If all of the connection factories are `DOWN`, the status should be `DOWN`?

**Comment by vsevel** [comment]
> If all of the connection factories are DOWN, the status should be DOWN?

it is a vast subject. in the company, we decided to disable most of the health checks, and extended them to map them onto `@Wellness`, then tie those to our alerting system.
and by default we even disabled the readiness probes for all of our apps. we have never seen a good reason to pull a single pod out of the pool.
so I actually understand that you would keep a status `UP`, even if a connection factory was `DOWN`, specifically if tied to the readiness probe.

**to me the proper way would be to have a check per connection factory, all tied to wellness.** 

this should not be a startup check because it does not prevent the app from starting, and work partially. it should not be readiness because it does not prevent the app from working partially, and it should not be liveness because a restart is not going to magically solve the loss of connectivity.
this is particularly true with the ra that has some resiliency built it (the app can start without connectivity, and it will later connect if available. and if loss of connectivity happens while the app is running, it will be able to reconnect as soon as the broker is available again).
my 2 cents.

**Comment by turing85** [comment]
> I now get:
> 
> ```
> $ curl localhost:9000/q/health/ready
>         {
>             "name": "Artemis JMS Resource Adaptor health check",
>             "status": "UP",
>             "data": {
>                 "<default>": "UP"
>             }
>         }
> ```
> 
> deps:
> 
> ```
> $ ls -al target/quarkus-app/lib/main | grep -E "artemis|iron"
> -rw-r--r-- 1 Sevel 1049089   22029 Aug  2 11:51 io.quarkiverse.artemis.quarkus-artemis-core-999-SNAPSHOT.jar
> -rw-r--r-- 1 Sevel 1049089   11146 Aug  2 11:51 io.quarkiverse.artemis.quarkus-artemis-jms-ra-999-SNAPSHOT.jar
> -rw-r--r-- 1 Sevel 1049089   53855 Aug  2 11:51 io.quarkiverse.ironjacamar.quarkus-ironjacamar-1.3.2.jar
> -rw-r--r-- 1 Sevel 1049089  676595 Aug  2 08:44 org.apache.activemq.artemis-commons-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089  829150 Aug  2 08:44 org.apache.activemq.artemis-core-client-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089   21552 Aug  2 08:44 org.apache.activemq.artemis-hqclient-protocol-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089  187781 Aug  2 08:44 org.apache.activemq.artemis-jakarta-client-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089  160114 Aug  2 08:44 org.apache.activemq.artemis-jakarta-ra-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089   33311 Aug  2 08:44 org.apache.activemq.artemis-jakarta-service-extensions-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089  112139 Aug  2 08:44 org.apache.activemq.artemis-selector-2.36.0.jar
> -rw-r--r-- 1 Sevel 1049089  103566 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-common-api-3.0.9.Final.jar
> -rw-r--r-- 1 Sevel 1049089   57849 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-core-api-3.0.9.Final.jar
> -rw-r--r-- 1 Sevel 1049089  502175 Apr 30 10:56 org.jboss.ironjacamar.ironjacamar-core-impl-3.0.9.Final.jar
> ```
> 
> seems everything is working nicely. what would you say that it only partially fixes the issue @zhfeng ? what would be still missing? some additional checks we could do in the artemis RA? I am surprised with the impl of:
> 
> ```
>     public HealthCheckResponse call() {
>         HealthCheckResponseBuilder builder = HealthCheckResponse.named("Artemis JMS Resource Adaptor health check").up();
>         for (String name : connectionFactoryNames) {
>             Annotation identifier = ArtemisUtil.toIdentifier(name);
>             try (Connection ignored = connectionFactories.select(identifier).get().createConnection()) {
>                 builder.withData(name, "UP");
>             } catch (Exception e) {
>                 builder.withData(name, "DOWN").down();
>             }
>         }
>         return builder.build();
>     }
> ```
> 
> do you want the status to be always `UP`? or should the status be `DOWN` as soon as at least one connection factory is down?

The check is not always up. The call to `down()` "downs" the complete check, not the data-item.
Calling 
```
builder.withData(name, "DOWN").down();
```
is the same as calling
```
builder.withData(name, "DOWN");
builder.down();
```

**Comment by vsevel** [comment]
yes you are right @turing85 I missed it.
so if one connection is down, the whole check is down. 
that is one possible behavior, consistent with others I have seen, even if I don't think this is the proper way of doing this. but this is a more general discussion. so I am fine with it.

**Comment by turing85** [comment]
@vsevel Believe me, I am on your side on this one. I triggered a discussion about this a while back. Don't remember where though. Either zulip or the mailing list.

**Comment by turing85** [comment]
So... is this MR ready4merge?

**Comment by vsevel** [comment]
> I triggered a discussion about this a while back

me too ;-) 
https://groups.google.com/g/quarkus-dev/c/pj6L7kzbIno/m/B4RXJcupBwAJ 

> So... is this MR ready4merge?

I think so. still not clear whether or not the initial issue is completely fixed.
@zhfeng what do you mean with _Now I think we almost get to fix the issue :)_?

**Comment by zhfeng** [comment]
Yeah, I think it is good to merge. @turing85 feel free to go ahead!

Thanks all for reviwing and @gastaldi for the quick release of `quarkus-ironjacamar`.

**Pull request merged**
