### PR TITLE
Remove io.quarkus:quarkus-jms-spi-deployment in build-parent

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
@turing85  I'd like to do a new release of `2.x` after merge this PR. WDYT?

**Comment by turing85** [comment]
> @turing85 I'd like to do a new release of `2.x` after merge this PR. WDYT?

@zhfend ythis is fine by me, yes. We should, however, create a ticket, so we do not forget to upstream the fix when the fix is done in `3.0.0`.

**Review by turing85 — APPROVED** [review]

**Comment by zhfeng** [comment]
Yeah, I raise a ticket for remvoing this dependency when Quarkus 3.0.0 has a new release.

**Comment by turing85** [comment]
@zhfeng `quarkus-artemis` [`2.0.5`](https://github.com/quarkiverse/quarkus-artemis/releases/tag/2.0.5) has been released.

**Comment by zhfeng** [comment]
@turing85 Well, this new release is not  backwards compatible because we change to use `ConnectionFactoryWrapperBuildItem` in `quarkus-jms-spi-deployment`. I wonder if we can bump to `2.1.0` at lease?

**Comment by turing85** [comment]
@zhfeng hmm... yes we can. But... I cannot undo what I have done, i.e. `2.0.5` will stay broken. Maybe do a `2.0.6` release, rolling back the changes, rolling back the rollback and do a `2.1.0` release?

**Comment by turing85** [comment]
@zhfeng In the mean time, I updated the release notes for version `2.0.5` and added the breaking change.

**Comment by zhfeng** [comment]
Thanks @turing85 and IMO, it could be good to just release `2.1.0` and no `2.0.x` anymore. @gastaldi we met this backwards compatible issue and just wonder what is the best way from the maintenance perspective?

**Comment by turing85** [comment]
@zhfeng okay, buildingt a `2.1.0` right now :+1:

**Comment by turing85** [comment]
@zhfeng quarkus-artemis version [`2.1.0`](https://github.com/quarkiverse/quarkus-artemis/releases/tag/2.1.0) has been [released](https://github.com/quarkiverse/quarkus-artemis/actions/runs/4243865234).

**Comment by middagj** [comment]
Let's wait until someone asks for it

**Pull request merged**
